language: node_js
node_js:
  - '4.1'

env:
  global:
    - secure: "LfcX7CHIye6M07e63EwFaR37r/e9q+5DIhro2fnrqgfJlcpYkZPFtm17cNks2imErGqKETiO0i5x/iuLpbTFZMYJ4PEU4xpyASSW9Ntku1JkxwuP7Jvd2nLwY7dNnP6GqzlRGQsMdF2slVOkhS8kp/MQdFFur+fvjkF9WYMP0+RTNi8awP650YEj8/RybFSGgPWAofV5gkZFa0KbcjyfBI+fZ5a+F1/VCa3Yev2S52My7so8vIF3crmpMpNC/n/Lh1NOmRaTiLPzpTJ9GMKi6vXrmeW99MGR/B98q3MMjj9ghTuwdcAm9EKor1icTWWA9EHBMpJiSgNu0eDf85Kb36XbUfDIJapWX3ia1/nwq/XBw3ttQjN24wQurUsqk816rPYQoL69ei8hVWvDgH44LKhXjDGMyO2maS1TG1cR4m2nEU2My2432SVEcjvrmsQzr9ZYBy1++/rIjIlstA7FnKSmqLE1EH+FcZb5f64AjtPpehYltMWNuGihp3AiPOibNfU/PK4umukxvisMNHtTvuYjgF5BqCA3IpeERaMROv/R2Hr1tVBrMMvwL0Kqk2gh+kqRjY5hyQO4v3LNhjfATbGefYTgigQ42UX/uDcmoG/+IscOamT9WG71NAPlm+UyWpoznvPGQAxCdxT2qA60FjsuNLI6fzp9J6Mj+ykGC9w="

before_install:
- gem update --system
- gem install compass
- npm install -g grunt-cli

install:
- 'npm install'

script:
- 'grunt build'

after_success:
- export GIT_DEPLOY_DIR=dist
- export GIT_DEPLOY_BRANCH=gh-pages
- export GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/ivarprudnikov/cms-angular-1.4.git
- source ./deploy_to_github.sh
- echo "Done deploy.sh"

